version: 2.1
workflows:
  main:
    jobs:
        
        #### UNIT TESTS
        - Linux:
            name: "Test | v3.8 | Linux"
            v: "3.8"
            mode: "TEST"
            
jobs:
  Linux:
    machine: true
    parameters:
      v:
        type: string
        default: "3.10"
      mode:
        type: string
        default: "ALL"
    resource_class: georgia-tech-db/testing
    
    steps:
      - run: echo "Hi I'm on Runners!"
      - checkout
      
      - run:
          name: Install EVA package from GitHub repo with all dependencies
          command: |
            "python<< parameters.v >>" -m venv test_evadb
            pip install --upgrade pip
            source test_evadb/bin/activate
            pip install ".[dev]"

      # Disable Ray for Coverage
      - when:
          condition:
            equal: [ COV, << parameters.mode >> ]
          steps:
            - run:
                name: Disable Ray setting in the config.yml file
                command: |
                  source test_evadb/bin/activate
                  python -c "import yaml;f = open('eva/eva.yml', 'r+');config_obj = yaml.load(f, Loader=yaml.FullLoader);config_obj['experimental']['ray'] = False;f.seek(0);f.write(yaml.dump(config_obj));f.truncate();"

      - run:
          name: Test and upload coverage report to coveralls
          no_output_timeout: 30m # 30 minute timeout
          command: |
            source test_evadb/bin/activate
            bash script/test/test.sh -m "<< parameters.mode >>"
