name: ❓ Question
description: Ask a EVA DB question
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        🙏 Thanks for asking a EVA DB Question!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        🔍 Please search the [issues](https://github.com/georgia-tech-db/eva/issues) to see if a similar question already exists.
      options:
        - label: >
            I have searched the EVA DB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar questions.
          required: true

  - type: textarea
    attributes:
      label: Question
      description: ❓ What is your question?
      placeholder: |
        💡 ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: 📝 Anything else you would like to share?
